import Papa from 'papaparse'

export const POS_MAP = {
  'Goalkeeper': 'GK',
  'Centre-Back': 'DF', 'Left-Back': 'DF', 'Right-Back': 'DF',
  'Defensive Midfield': 'MF', 'Central Midfield': 'MF', 'Attacking Midfield': 'MF',
  'Left Midfield': 'MF', 'Right Midfield': 'MF',
  'Left Winger': 'FW', 'Right Winger': 'FW', 'Centre-Forward': 'FW', 'Second Striker': 'FW',
}

export const POS_ES = {
  GK: 'Portero',
  DF: 'Defensa',
  MF: 'Centrocampista',
  FW: 'Delantero',
}

export async function loadPlayers() {
  return new Promise((resolve, reject) => {
    Papa.parse('/data/bbdd_mundial_nacimiento_localizado.csv', {
      download: true,
      header: true,
      dynamicTyping: true,
      skipEmptyLines: true,
      transformHeader: h => h.replace(/^﻿/, ''),
      complete: ({ data }) => resolve(data.filter(r => r.player_tm)),
      error: reject,
    })
  })
}

export function formatMV(value) {
  const v = Number(value)
  if (!value || isNaN(v)) return '—'
  if (v >= 1_000_000) return `€${(v / 1_000_000).toFixed(0)}M`
  if (v >= 1_000) return `€${Math.round(v / 1_000)}k`
  return `€${v}`
}

export function formatDOB(dob) {
  if (!dob) return '—'
  const parts = String(dob).split('-')
  if (parts.length !== 3) return dob
  return `${parts[2]}/${parts[1]}/${parts[0]}`
}

// Nombres de países en español (clave = nombre en inglés del CSV)
const COUNTRY_ES = {
  // Las 48 selecciones
  'Algeria':                          'Argelia',
  'Argentina':                        'Argentina',
  'Australia':                        'Australia',
  'Austria':                          'Austria',
  'Belgium':                          'Bélgica',
  'Bosnia-Herzegovina':               'Bosnia y Herzegovina',
  'Brazil':                           'Brasil',
  'Canada':                           'Canadá',
  'Cape Verde':                       'Cabo Verde',
  'Colombia':                         'Colombia',
  'Croatia':                          'Croacia',
  'Curaçao':                          'Curazao',
  'Czechia':                          'República Checa',
  'Democratic Republic of the Congo': 'RD del Congo',
  'Ecuador':                          'Ecuador',
  'Egypt':                            'Egipto',
  'England':                          'Inglaterra',
  'France':                           'Francia',
  'Germany':                          'Alemania',
  'Ghana':                            'Ghana',
  'Haiti':                            'Haití',
  'Iran':                             'Irán',
  'Iraq':                             'Irak',
  'Ivory Coast':                      'Costa de Marfil',
  'Japan':                            'Japón',
  'Jordan':                           'Jordania',
  'Mexico':                           'México',
  'Morocco':                          'Marruecos',
  'Netherlands':                      'Países Bajos',
  'New Zealand':                      'Nueva Zelanda',
  'Norway':                           'Noruega',
  'Panama':                           'Panamá',
  'Paraguay':                         'Paraguay',
  'Portugal':                         'Portugal',
  'Qatar':                            'Catar',
  'Saudi Arabia':                     'Arabia Saudí',
  'Scotland':                         'Escocia',
  'Senegal':                          'Senegal',
  'South Africa':                     'Sudáfrica',
  'South Korea':                      'República de Corea',
  'Spain':                            'España',
  'Sweden':                           'Suecia',
  'Switzerland':                      'Suiza',
  'Tunisia':                          'Túnez',
  'Turkiye':                          'Turquía',
  'United States':                    'Estados Unidos',
  'Uruguay':                          'Uruguay',
  'Uzbekistan':                       'Uzbekistán',

  // Países de nacimiento frecuentes (no clasificados)
  'Wales':                      'Gales',
  'Northern Ireland':           'Irlanda del Norte',
  'Ireland':                    'Irlanda',
  'Italy':                      'Italia',
  'Russia':                     'Rusia',
  'Ukraine':                    'Ucrania',
  'Poland':                     'Polonia',
  'Denmark':                    'Dinamarca',
  'Serbia':                     'Serbia',
  'Hungary':                    'Hungría',
  'Romania':                    'Rumanía',
  'Bulgaria':                   'Bulgaria',
  'Greece':                     'Grecia',
  'Turkey':                     'Turquía',
  'China':                      'China',
  'China PR':                   'China',
  'India':                      'India',
  'Indonesia':                  'Indonesia',
  'Nigeria':                    'Nigeria',
  'Cameroon':                   'Camerún',
  'Senegal':                    'Senegal',
  'Mali':                       'Malí',
  'Guinea':                     'Guinea',
  'Guinea-Bissau':              'Guinea-Bisáu',
  'Equatorial Guinea':          'Guinea Ecuatorial',
  'Gabon':                      'Gabón',
  'Congo':                      'Congo',
  'Angola':                     'Angola',
  'Mozambique':                 'Mozambique',
  'Zimbabwe':                   'Zimbabue',
  'Uganda':                     'Uganda',
  'Rwanda':                     'Ruanda',
  'Somalia':                    'Somalia',
  'Sudan':                      'Sudán',
  'South Sudan':                'Sudán del Sur',
  'Ethiopia':                   'Etiopía',
  'Tanzania':                   'Tanzania',
  'Kenya':                      'Kenia',
  'Zambia':                     'Zambia',
  'Malawi':                     'Malaui',
  'Botswana':                   'Botsuana',
  'Namibia':                    'Namibia',
  'Togo':                       'Togo',
  'Benin':                      'Benín',
  'Niger':                      'Níger',
  'Chad':                       'Chad',
  'Libya':                      'Libia',
  'Eritrea':                    'Eritrea',
  'Djibouti':                   'Yibuti',
  'Burkina Faso':               'Burkina Faso',
  'Comoros':                    'Comoras',
  'Madagascar':                 'Madagascar',
  'Venezuela':                  'Venezuela',
  'Chile':                      'Chile',
  'Bolivia':                    'Bolivia',
  'Peru':                       'Perú',
  'Cuba':                       'Cuba',
  'Jamaica':                    'Jamaica',
  'Dominican Republic':         'República Dominicana',
  'Honduras':                   'Honduras',
  'Guatemala':                  'Guatemala',
  'El Salvador':                'El Salvador',
  'Nicaragua':                  'Nicaragua',
  'Costa Rica':                 'Costa Rica',
  'Trinidad and Tobago':        'Trinidad y Tobago',
  'French Guiana':              'Guayana Francesa',
  'Suriname':                   'Surinam',
  'Guyana':                     'Guyana',
  'Martinique':                 'Martinica',
  'Guadeloupe':                 'Guadalupe',
  'United Kingdom':             'Reino Unido',
  'Israel':                     'Israel',
  'Palestine':                  'Palestina',
  'Lebanon':                    'Líbano',
  'Syria':                      'Siria',
  'United Arab Emirates':       'Emiratos Árabes Unidos',
  'Kuwait':                     'Kuwait',
  'Bahrain':                    'Baréin',
  'Oman':                       'Omán',
  'Yemen':                      'Yemen',
  'Kazakhstan':                 'Kazajistán',
  'Kyrgyzstan':                 'Kirguistán',
  'Tajikistan':                 'Tayikistán',
  'Turkmenistan':               'Turkmenistán',
  'Azerbaijan':                 'Azerbaiyán',
  'Georgia':                    'Georgia',
  'Armenia':                    'Armenia',
  'Belarus':                    'Bielorrusia',
  'Moldova':                    'Moldavia',
  'Slovakia':                   'Eslovaquia',
  'Slovenia':                   'Eslovenia',
  'North Macedonia':            'Macedonia del Norte',
  'Bosnia and Herzegovina':     'Bosnia y Herzegovina',
  'Montenegro':                 'Montenegro',
  'Kosovo':                     'Kosovo',
  'Albania':                    'Albania',
  'Finland':                    'Finlandia',
  'Estonia':                    'Estonia',
  'Latvia':                     'Letonia',
  'Lithuania':                  'Lituania',
  'Luxembourg':                 'Luxemburgo',
  'Iceland':                    'Islandia',
  'Vietnam':                    'Vietnam',
  'Thailand':                   'Tailandia',
  'Malaysia':                   'Malasia',
  'Philippines':                'Filipinas',
  'Singapore':                  'Singapur',
  'South Korea':                'República de Corea',
  'North Korea':                'Corea del Norte',
  'New Caledonia':              'Nueva Caledonia',
  'Papua New Guinea':           'Papúa Nueva Guinea',
  'Fiji':                       'Fiyi',
}

export function t(name) {
  if (!name) return name
  return COUNTRY_ES[name] ?? name
}
